import javafx.application.Application;
import javafx.fxml.FXMLLoader;
import javafx.scene.Scene;
import javafx.scene.layout.VBox;
import javafx.stage.Stage;

import java.io.IOException;
import java.net.URI;
import java.net.URISyntaxException;
import java.net.URL;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.Enumeration;
import java.util.jar.JarEntry;
import java.util.jar.JarFile;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class App extends Application {

    public static void main(String[] args) {
        launch(args);
    }
    @Override
    public void start(Stage primaryStage) throws Exception {
        try {
            URL jarLocation = App.class.getProtectionDomain().getCodeSource().getLocation();
            URI jarLocationUri = null;
            jarLocationUri = jarLocation.toURI();
            Path jarLocationPath = Paths.get(jarLocationUri);
            Path jarLocationAbsolutePath = jarLocationPath.toAbsolutePath();
            String jarLocationAbsolutePathStr = jarLocationAbsolutePath.toString();
            System.out.println(jarLocationAbsolutePathStr);
            JarFile jarArchive = new JarFile(jarLocationAbsolutePathStr);
            Enumeration<JarEntry> jarEntries = jarArchive.entries();

//            while( jarEntries.hasMoreElements() ) {
//                JarEntry jarEntry = jarEntries.nextElement();
//                System.out.println(jarEntry.toString());
//            }
            URL jarFxmlConnection = new URL("jar:file://"+
                    jarLocationAbsolutePathStr+"/fxml/hello-world.fxml");
            FXMLLoader loader = new FXMLLoader();
            loader.setLocation(jarFxmlConnection);
            VBox vbox = loader.<VBox>load();
            Scene scene = new Scene(vbox);
            primaryStage.setScene(scene);
            primaryStage.show();
        } catch (URISyntaxException | IOException e) {
            e.printStackTrace();
        }
    }
}
